networks:
  ts99-net:
    driver: bridge
    ipam:
      config:
        - subnet: 172.129.0.0/24

volumes:
  ts99-node1-data:
  ts99-node2-data:
  ts99-node3-data:
  ts99-node4-data:
  ts99-node5-data:
  ts99-blobstore:

x-teraslab-common: &teraslab-common
  image: teraslab:test
  restart: "no"
  cap_add:
    - NET_ADMIN
  ulimits:
    memlock:
      soft: -1
      hard: -1

services:
  node1:
    <<: *teraslab-common
    container_name: ts99-node1
    hostname: node1
    networks:
      ts99-net:
        ipv4_address: 172.129.0.11
    volumes:
      - ts99-node1-data:/data
      - ts99-blobstore:/blobstore
      - /Users/siggioskarsson/gitcheckout/teraslab/teraslab-tests/client/../docker/config/ts99-node1.toml:/etc/teraslab/node.toml:ro
    ports:
      - "13990:3300"
      - "19990:9100"
  node2:
    <<: *teraslab-common
    container_name: ts99-node2
    hostname: node2
    networks:
      ts99-net:
        ipv4_address: 172.129.0.12
    volumes:
      - ts99-node2-data:/data
      - ts99-blobstore:/blobstore
      - /Users/siggioskarsson/gitcheckout/teraslab/teraslab-tests/client/../docker/config/ts99-node2.toml:/etc/teraslab/node.toml:ro
    ports:
      - "13991:3300"
      - "19991:9100"
  node3:
    <<: *teraslab-common
    container_name: ts99-node3
    hostname: node3
    networks:
      ts99-net:
        ipv4_address: 172.129.0.13
    volumes:
      - ts99-node3-data:/data
      - ts99-blobstore:/blobstore
      - /Users/siggioskarsson/gitcheckout/teraslab/teraslab-tests/client/../docker/config/ts99-node3.toml:/etc/teraslab/node.toml:ro
    ports:
      - "13992:3300"
      - "19992:9100"
  node4:
    <<: *teraslab-common
    container_name: ts99-node4
    hostname: node4
    networks:
      ts99-net:
        ipv4_address: 172.129.0.14
    volumes:
      - ts99-node4-data:/data
      - ts99-blobstore:/blobstore
      - /Users/siggioskarsson/gitcheckout/teraslab/teraslab-tests/client/../docker/config/ts99-node4.toml:/etc/teraslab/node.toml:ro
    ports:
      - "13993:3300"
      - "19993:9100"
  node5:
    <<: *teraslab-common
    container_name: ts99-node5
    hostname: node5
    networks:
      ts99-net:
        ipv4_address: 172.129.0.15
    volumes:
      - ts99-node5-data:/data
      - ts99-blobstore:/blobstore
      - /Users/siggioskarsson/gitcheckout/teraslab/teraslab-tests/client/../docker/config/ts99-node5.toml:/etc/teraslab/node.toml:ro
    ports:
      - "13994:3300"
      - "19994:9100"
