networks:
  ts09-net:
    driver: bridge
    ipam:
      config:
        - subnet: 172.39.0.0/24

volumes:
  ts09-node1-data:
  ts09-node2-data:
  ts09-node3-data:
  ts09-node4-data:
  ts09-node5-data:
  ts09-blobstore:

x-teraslab-common: &teraslab-common
  image: teraslab:test
  restart: "no"
  cap_add:
    - NET_ADMIN
  ulimits:
    memlock:
      soft: -1
      hard: -1

services:
  node1:
    <<: *teraslab-common
    container_name: ts09-node1
    hostname: node1
    networks:
      ts09-net:
        ipv4_address: 172.39.0.11
    volumes:
      - ts09-node1-data:/data
      - ts09-blobstore:/blobstore
      - /Users/siggioskarsson/gitcheckout/teraslab/teraslab-tests/client/../docker/config/ts09-node1.toml:/etc/teraslab/node.toml:ro
    ports:
      - "13090:3300"
      - "19090:9100"
  node2:
    <<: *teraslab-common
    container_name: ts09-node2
    hostname: node2
    networks:
      ts09-net:
        ipv4_address: 172.39.0.12
    volumes:
      - ts09-node2-data:/data
      - ts09-blobstore:/blobstore
      - /Users/siggioskarsson/gitcheckout/teraslab/teraslab-tests/client/../docker/config/ts09-node2.toml:/etc/teraslab/node.toml:ro
    ports:
      - "13091:3300"
      - "19091:9100"
  node3:
    <<: *teraslab-common
    container_name: ts09-node3
    hostname: node3
    networks:
      ts09-net:
        ipv4_address: 172.39.0.13
    volumes:
      - ts09-node3-data:/data
      - ts09-blobstore:/blobstore
      - /Users/siggioskarsson/gitcheckout/teraslab/teraslab-tests/client/../docker/config/ts09-node3.toml:/etc/teraslab/node.toml:ro
    ports:
      - "13092:3300"
      - "19092:9100"
  node4:
    <<: *teraslab-common
    container_name: ts09-node4
    hostname: node4
    networks:
      ts09-net:
        ipv4_address: 172.39.0.14
    volumes:
      - ts09-node4-data:/data
      - ts09-blobstore:/blobstore
      - /Users/siggioskarsson/gitcheckout/teraslab/teraslab-tests/client/../docker/config/ts09-node4.toml:/etc/teraslab/node.toml:ro
    ports:
      - "13093:3300"
      - "19093:9100"
  node5:
    <<: *teraslab-common
    container_name: ts09-node5
    hostname: node5
    networks:
      ts09-net:
        ipv4_address: 172.39.0.15
    volumes:
      - ts09-node5-data:/data
      - ts09-blobstore:/blobstore
      - /Users/siggioskarsson/gitcheckout/teraslab/teraslab-tests/client/../docker/config/ts09-node5.toml:/etc/teraslab/node.toml:ro
    ports:
      - "13094:3300"
      - "19094:9100"
